name: reddust-reclaimer
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.9
  # Core scientific computing
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - plotly>=5.0.0
  - jupyter>=1.0.0
  
  # Bioinformatics tools
  - biopython>=1.79
  - blast>=2.12.0
  - muscle>=3.8.1551
  - clustalw>=2.1
  - hmmer>=3.3.2
  - autodock-vina>=1.2.0
  
  # Computational biology
  - cobra>=0.26.0
  - biotite>=0.37.0
  - mdanalysis>=2.0.0
  
  # Machine learning
  - scikit-learn>=1.0.0
  - tensorflow>=2.8.0
  - pytorch>=1.11.0
  
  # Molecular modeling
  - prody>=2.0.0
  - mdtraj>=1.9.0
  
  # Parallel computing
  - joblib>=1.1.0
  - dask>=2022.0.0
  
  # Database and file handling
  - sqlalchemy>=1.4.0
  - h5py>=3.6.0
  - openpyxl>=3.0.0
  
  # Web tools
  - requests>=2.28.0
  - beautifulsoup4>=4.11.0
  
  # Visualization
  - graphviz>=0.20.0
  - networkx>=2.8.0
  - bokeh>=2.4.0
  
  # Documentation
  - sphinx>=4.5.0
  
  # Development tools
  - pytest>=7.0.0
  - black>=22.0.0
  - flake8>=4.0.0
  
  # Pip dependencies not available in conda
  - pip
  - pip:
    - pymol-open3d>=2.5.0
    - primer3-py>=0.6.0
    - snapgene-reader>=0.1.0
    - astropy>=5.0.0
    - planetarypy>=0.7.0
    - pytraj>=2.0.0
    - optuna>=3.0.0