name: 🚀 Feature Request
description: Suggest a new feature for reddust-reclaimer
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to see added?
      placeholder: Describe the feature you'd like to request...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component Area
      description: Which area would this feature enhance?
      options:
        - Molecular Docking
        - Codon Optimization
        - Metabolic Modeling
        - Data Processing
        - Visualization
        - Documentation
        - Performance
        - New Module
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature be used in Mars terraforming research?
      placeholder: |
        Example: This feature would help researchers...
        - Analyze protein stability under Mars conditions
        - Optimize metabolic pathways for CO2 processing
        - Visualize docking results in 3D
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you think this feature should be implemented?
      placeholder: |
        Optional: Describe your ideas for implementation
        - API design suggestions
        - Algorithm preferences
        - Integration points

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical - Blocks research progress
        - High - Significantly improves workflow
        - Medium - Nice to have improvement
        - Low - Minor enhancement
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues for similar requests
          required: true
        - label: This feature aligns with Mars terraforming research goals
          required: true
        - label: I have provided a clear use case description
          required: true
