# .gitlab-ci.yml
image: python:3.10

stages:
  - lint
  - test
  - docs
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

# Lint stage - runs once
lint:
  stage: lint
  image: python:3.10
  script:
    - pip install flake8 black isort
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - black --check --diff .
    - isort --check-only --diff .
  allow_failure: true

# Test matrix - full Python version coverage
.test_template: &test_template
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install pytest pytest-cov
    - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - if [ -f environment.yml ]; then pip install pyyaml && python -c "import yaml; deps=yaml.safe_load(open('environment.yml'))['dependencies']; [print(d) for d in deps if isinstance(d, str) and '=' in d]" | xargs pip install; fi
  script:
    - pytest --cov=. --cov-report=xml --cov-report=html
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - htmlcov/
    expire_in: 1 week

test_python38:
  <<: *test_template
  image: python:3.8

test_python39:
  <<: *test_template
  image: python:3.9

test_python310:
  <<: *test_template
  image: python:3.10

test_python311:
  <<: *test_template
  image: python:3.11

# Conda environment test
test_conda:
  stage: test
  image: continuumio/miniconda3:latest
  script:
    - conda env create -f environment.yml -n testenv
    - source activate testenv
    - python -c "import numpy, pandas, biopython; print('✅ Conda environment working')"
    - pytest
  only:
    changes:
      - environment.yml
      - "*.py"

# Documentation build
docs:
  stage: docs
  image: python:3.10
  script:
    - pip install mkdocs mkdocs-material
    - mkdocs build --strict
  artifacts:
    paths:
      - site/
    expire_in: 1 week
  only:
    - main

# Deploy to GitLab Pages (bonus!)
pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r site/* public/
  artifacts:
    paths:
      - public
  only:
    - main
  dependencies:
    - docs
